#!/usr/bin/env python

# Copyright 2024 The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Records a dataset for `ae_robot` (single-arm) or `bi_ae_robot` (dual-arm).
Actions for the robot can be either generated by teleoperation or by a policy,
with support for teleoperation intervention.

Example: Record with single SpaceMouse teleoperation only (for single-arm ae_robot)

```shell
lerobot-record-aerobot \
    --robot.type=ae_robot \
    --teleop.type=spacemouse \
    --dataset.repo_id="<my_username>/<my_dataset_name>" \
    --dataset.single_task="Push the cube"
```

Example: Record with dual SpaceMouse teleoperation only (for dual-arm bi_ae_robot)

```shell
lerobot-record-aerobot \
    --robot.type=bi_ae_robot \
    --robot.left_arm_config.server_url="http://127.0.0.1:5000" \
    --robot.right_arm_config.server_url="http://127.0.0.1:5001" \
    --teleop.type=bi_spacemouse \
    --dataset.repo_id="<my_username>/<my_dataset_name>" \
    --dataset.single_task="Push the cube with two arms"
```

Example: Record with a policy and single Meta Quest intervention (for single-arm ae_robot)

```shell
lerobot-record-aerobot \
    --robot.type=ae_robot \
    --policy.path=<path_to_policy> \
    --teleop.type=meta_quest \
    --dataset.repo_id="<my_username>/<my_dataset_name>" \
    --dataset.single_task="Push the cube"
```

Example: Record with a policy and dual Meta Quest intervention (for dual-arm bi_ae_robot)

```shell
lerobot-record-aerobot \
    --robot.type=bi_ae_robot \
    --robot.left_arm_config.server_url="http://127.0.0.1:5000" \
    --robot.right_arm_config.server_url="http://127.0.0.1:5001" \
    --policy.path=<path_to_policy> \
    --teleop.type=bi_meta_quest \
    --dataset.repo_id="<my_username>/<my_dataset_name>" \
    --dataset.single_task="Push the cube with two arms"
```
"""

import logging
import time
from dataclasses import asdict, dataclass, field
from pathlib import Path
from pprint import pformat
from typing import Any

import numpy as np

from lerobot.cameras import CameraConfig
from lerobot.cameras.opencv.configuration_opencv import OpenCVCameraConfig
from lerobot.cameras.realsense.configuration_realsense import RealSenseCameraConfig
from lerobot.configs import parser
from lerobot.configs.policies import PreTrainedConfig
from lerobot.datasets.image_writer import safe_stop_image_writer
from lerobot.datasets.lerobot_dataset import LeRobotDataset
from lerobot.datasets.pipeline_features import aggregate_pipeline_dataset_features, create_initial_features
from lerobot.datasets.utils import (
    build_dataset_frame,
    combine_feature_dicts,
    hw_to_dataset_features,
)
from lerobot.datasets.video_utils import VideoEncodingManager
from lerobot.policies.factory import make_policy, make_pre_post_processors
from lerobot.policies.pretrained import PreTrainedPolicy
from lerobot.policies.utils import make_robot_action
from lerobot.processor import (
    PolicyAction,
    PolicyProcessorPipeline,
    RobotAction,
    RobotObservation,
    RobotProcessorPipeline,
    make_default_processors,
)
from lerobot.processor.rename_processor import rename_stats
from lerobot.robots import Robot, RobotConfig, ae_robot, make_robot_from_config
from lerobot.teleoperators import (
    Teleoperator,
    TeleoperatorConfig,
    make_teleoperator_from_config,
    meta_quest,
    spacemouse,
)
from lerobot.utils.constants import ACTION, OBS_STR
from lerobot.utils.control_utils import (
    init_keyboard_listener,
    is_headless,
    predict_action,
    sanity_check_dataset_name,
    sanity_check_dataset_robot_compatibility,
)
from lerobot.utils.import_utils import is_rclpy_available, register_third_party_devices
from lerobot.utils.robot_utils import busy_wait as precise_sleep
from lerobot.utils.utils import get_safe_torch_device, init_logging, log_say
from lerobot.utils.visualization_utils import init_rerun, log_rerun_data

if is_rclpy_available():
    import rclpy


@dataclass
class DatasetRecordConfig:
    repo_id: str
    single_task: str
    root: str | Path | None = None
    fps: int = 30
    episode_time_s: int | float = 60
    reset_time_s: int | float = 10
    num_episodes: int = 50
    video: bool = True
    push_to_hub: bool = True
    private: bool = False
    tags: list[str] | None = None
    num_image_writer_processes: int = 0
    num_image_writer_threads_per_camera: int = 4
    video_encoding_batch_size: int = 1
    rename_map: dict[str, str] = field(default_factory=dict)

    def __post_init__(self):
        if self.single_task is None:
            raise ValueError("You need to provide a task as argument in `single_task`.")


@dataclass
class RecordConfig:
    robot: RobotConfig
    dataset: DatasetRecordConfig
    teleop: TeleoperatorConfig | None = None
    policy: PreTrainedConfig | None = None
    display_data: bool = False
    play_sounds: bool = True
    resume: bool = False

    def __post_init__(self):
        policy_path = parser.get_path_arg("policy")
        if policy_path:
            cli_overrides = parser.get_cli_overrides("policy")
            self.policy = PreTrainedConfig.from_pretrained(policy_path, cli_overrides=cli_overrides)
            self.policy.pretrained_path = policy_path

        if self.teleop is None and self.policy is None:
            raise ValueError("Choose a policy, a teleoperator or both to control the robot")

    @classmethod
    def __get_path_fields__(cls) -> list[str]:
        return ["policy"]


@safe_stop_image_writer
def record_loop(
    robot: Robot,
    events: dict,
    fps: int,
    teleop_action_processor: RobotProcessorPipeline,
    robot_action_processor: RobotProcessorPipeline,
    robot_observation_processor: RobotProcessorPipeline,
    dataset: LeRobotDataset | None = None,
    teleop: Teleoperator | None = None,
    policy: PreTrainedPolicy | None = None,
    preprocessor: PolicyProcessorPipeline | None = None,
    postprocessor: PolicyProcessorPipeline | None = None,
    control_time_s: int | None = None,
    single_task: str | None = None,
    display_data: bool = False,
    use_intervention: bool = False,
):
    if dataset is not None and dataset.fps != fps:
        raise ValueError(f"The dataset fps should be equal to requested fps ({dataset.fps} != {fps}).")

    if policy is not None and preprocessor is not None and postprocessor is not None:
        policy.reset()
        preprocessor.reset()
        postprocessor.reset()

    timestamp = 0
    start_episode_t = time.perf_counter()
    while timestamp < control_time_s:
        start_loop_t = time.perf_counter()

        if events["exit_early"]:
            events["exit_early"] = False
            break

        obs = robot.get_observation()
        obs_processed = robot_observation_processor(obs)

        # Prepare observation for policy if needed
        observation_frame = None
        if dataset is not None:
            observation_frame = build_dataset_frame(dataset.features, obs_processed, prefix=OBS_STR)


        final_action_values = None
        intervened = False

        if teleop and use_intervention:
            raw_teleop_action, buttons = teleop.get_raw_action()
            # Intervention is defined as any button press or significant joystick movement
            # 0.01 threshold for joystick movement (arbitrary, can be tuned)
            if np.any(buttons) or np.linalg.norm(raw_teleop_action) > 0.01:
                intervened = True
                
        if intervened:
            act = teleop.get_action() # This gets the processed action with gripper
            final_action_values = teleop_action_processor((act, obs))
        elif policy is not None:
            # Fallback to policy action if no intervention
            final_action_values = predict_action(
                observation=observation_frame,
                policy=policy,
                device=get_safe_torch_device(policy.config.device),
                preprocessor=preprocessor,
                postprocessor=postprocessor,
                use_amp=policy.config.use_amp,
                task=single_task,
                robot_type=robot.robot_type,
            )
        elif teleop is not None: # No policy, so teleop is the primary control
            act = teleop.get_action()
            final_action_values = teleop_action_processor((act, obs))
        else: # No policy, no teleop
            logging.info("No policy or teleoperator provided, sending zero action.")
            # Send a zero action to keep the robot still
            # Initialize with default action features, then fill with zeros
            default_action_features = {
                k: np.zeros(v) if isinstance(v, tuple) else np.array([0.0])
                for k, v in robot.action_features.items()
            }
            final_action_values = make_robot_action(default_action_features, dataset.features)


        robot_action_to_send = robot_action_processor((final_action_values, obs))
        robot.send_action(robot_action_to_send)

        if dataset is not None:
            action_frame = build_dataset_frame(dataset.features, final_action_values, prefix=ACTION)
            frame = {**observation_frame, **action_frame, "task": single_task}
            dataset.add_frame(frame)

        if display_data:
            log_rerun_data(observation=obs_processed, action=final_action_values)

        dt_s = time.perf_counter() - start_loop_t
        precise_sleep(1 / fps - dt_s)

        timestamp = time.perf_counter() - start_episode_t


@parser.wrap()
def record(cfg: RecordConfig) -> LeRobotDataset:
    init_logging()
    logging.info(pformat(asdict(cfg)))
    if cfg.display_data:
        init_rerun(session_name="recording")

    # Initialize rclpy if Meta Quest teleop is used
    if cfg.teleop and (cfg.teleop.type == "meta_quest" or cfg.teleop.type == "bi_meta_quest"):
        if not is_rclpy_available():
            raise ImportError("rclpy is required for Meta Quest teleop. Please install ROS2.")
        # rclpy.init() should be called only once and before any rclpy nodes are created
        # In this setup, QuestExpertProcess handles rclpy.init() and shutdown() in its own process.
        # So we just ensure the dependency is met.
        pass

    robot = make_robot_from_config(cfg.robot)
    teleop = make_teleoperator_from_config(cfg.teleop) if cfg.teleop is not None else None

    teleop_action_processor, robot_action_processor, robot_observation_processor = make_default_processors()

    action_features = hw_to_dataset_features(
        robot.action_features, prefix=ACTION, use_video=cfg.dataset.video
    )
    observation_features = hw_to_dataset_features(
        robot.observation_features, prefix=OBS_STR, use_video=cfg.dataset.video
    )
    dataset_features = combine_feature_dicts(action_features, observation_features)

    dataset = None
    listener = None

    try:
        if cfg.resume:
            dataset = LeRobotDataset(
                cfg.dataset.repo_id,
                root=cfg.dataset.root,
                batch_encoding_size=cfg.dataset.video_encoding_batch_size,
            )
            if hasattr(robot, "cameras") and len(robot.cameras) > 0:
                dataset.start_image_writer(
                    num_processes=cfg.dataset.num_image_writer_processes,
                    num_threads=cfg.dataset.num_image_writer_threads_per_camera * len(robot.cameras),
                )
            sanity_check_dataset_robot_compatibility(dataset, robot, cfg.dataset.fps, dataset_features)
        else:
            sanity_check_dataset_name(cfg.dataset.repo_id, cfg.policy)
            dataset = LeRobotDataset.create(
                cfg.dataset.repo_id,
                cfg.dataset.fps,
                root=cfg.dataset.root,
                robot_type=robot.name,
                features=dataset_features,
                use_videos=cfg.dataset.video,
                image_writer_processes=cfg.dataset.num_image_writer_processes,
                image_writer_threads=cfg.dataset.num_image_writer_threads_per_camera
                * (len(robot.cameras) if hasattr(robot, "cameras") else 0),
                batch_encoding_size=cfg.dataset.video_encoding_batch_size,
            )

        policy = None if cfg.policy is None else make_policy(cfg.policy, ds_meta=dataset.meta)
        preprocessor = None
        postprocessor = None
        if cfg.policy is not None:
            preprocessor, postprocessor = make_pre_post_processors(
                policy_cfg=cfg.policy,
                pretrained_path=cfg.policy.pretrained_path,
                dataset_stats=rename_stats(dataset.meta.stats, cfg.dataset.rename_map),
                preprocessor_overrides={
                    "device_processor": {"device": cfg.policy.device},
                    "rename_observations_processor": {"rename_map": cfg.dataset.rename_map},
                },
            )

        robot.connect()
        if teleop is not None:
            teleop.connect()

        listener, events = init_keyboard_listener()

        # Determine if intervention logic should be active
        use_intervention = teleop is not None and policy is not None

        with VideoEncodingManager(dataset):
            recorded_episodes = 0
            while recorded_episodes < cfg.dataset.num_episodes and not events["stop_recording"]:
                log_say(f"Recording episode {recorded_episodes + 1}/{cfg.dataset.num_episodes}", cfg.play_sounds)
                record_loop(
                    robot=robot,
                    events=events,
                    fps=cfg.dataset.fps,
                    teleop_action_processor=teleop_action_processor,
                    robot_action_processor=robot_action_processor,
                    robot_observation_processor=robot_observation_processor,
                    teleop=teleop,
                    policy=policy,
                    preprocessor=preprocessor,
                    postprocessor=postprocessor,
                    dataset=dataset,
                    control_time_s=cfg.dataset.episode_time_s,
                    single_task=cfg.dataset.single_task,
                    display_data=cfg.display_data,
                    use_intervention=use_intervention,
                )

                if not events["stop_recording"] and (
                    (recorded_episodes < cfg.dataset.num_episodes - 1) or events["rerecord_episode"]
                ):
                    log_say("Reset the environment", cfg.play_sounds)
                    # Reset phase never uses intervention, only primary teleop or no action
                    record_loop(
                        robot=robot,
                        events=events,
                        fps=cfg.dataset.fps,
                        teleop_action_processor=teleop_action_processor,
                        robot_action_processor=robot_action_processor,
                        robot_observation_processor=robot_observation_processor,
                        teleop=teleop, # Teleop can be used for manual reset if no policy
                        policy=None, # Policy is explicitly not used during reset phase
                        preprocessor=None,
                        postprocessor=None,
                        dataset=None, # No recording during reset phase
                        control_time_s=cfg.dataset.reset_time_s,
                        single_task=cfg.dataset.single_task,
                        display_data=cfg.display_data,
                        use_intervention=False,
                    )

                if events["rerecord_episode"]:
                    log_say("Re-record episode", cfg.play_sounds)
                    events["rerecord_episode"] = False
                    events["exit_early"] = False
                    dataset.clear_episode_buffer()
                    continue

                dataset.save_episode()
                recorded_episodes += 1
    finally:
        log_say("Stop recording", cfg.play_sounds, blocking=True)

        if dataset:
            dataset.finalize()

        if robot.is_connected:
            robot.disconnect()
        if teleop and teleop.is_connected:
            teleop.disconnect()

        if not is_headless() and listener:
            listener.stop()

        if cfg.dataset.push_to_hub:
            dataset.push_to_hub(tags=cfg.dataset.tags, private=cfg.dataset.private)

        # Explicitly shutdown rclpy if it was initialized for Meta Quest
        if cfg.teleop and (cfg.teleop.type == "meta_quest" or cfg.teleop.type == "bi_meta_quest") and is_rclpy_available():
            # rclpy.shutdown() is handled by QuestExpertProcess when its process terminates.
            # No need to call it here in the main thread.
            pass

        log_say("Exiting", cfg.play_sounds)
    return dataset


def main():
    register_third_party_devices()
    record()


if __name__ == "__main__":
    main()
