# Example YAML configuration for BiAERobot with personalized arm parameters.
# You can save this to a file and pass it to the script.
#
# lerobot-record-aerobot --config-path comprehensive_aerobot_record_config.yaml ...
#

# policy:
#   path: home/ae/project/lerobot/outputs/pi05_ae_260107_alpha/checkpoints/020000/pretrained_model
robot:
  type: bi_ae_robot
  left_arm_config:
    server_url: "http://192.168.2.22:5003" # IP address for the left arm's server
    action_scale: [0.05, 0.15, 1.0]           # Custom action scale for the left arm
    reset_pose: [0.35351,0.223,0.3, 3.08,  -1.0 , 1.6] # Custom reset pose for the left arm
    workspace_limits: {
            "low": [0.25351,0.22,0.02, 3.08,  -1.2 , 1.6],
            "high": [0.4851,0.3086857331173238,0.3469930313903671, 3.08,  -1.0 , 1.6],
        }
    gripper_open_width: 0.03                # Custom gripper open width for the left arm
    cameras:                                # Custom camera configuration for the left arm
      wrist_cam:
        type: opencv
        index_or_path: 2
        width: 640
        height: 480
        fps: 30
      side_cam:
        type: opencv
        index_or_path: 22
        width: 640
        height: 480
        fps: 30
  right_arm_config:
    server_url: "http://192.168.2.22:5002" # IP address for the right arm's server
    action_scale: [0.05, 0.15, 1.0]           # Custom action scale for the right arm
    reset_pose: [0.35469, -0.179459, -0.0000, 3.03, -1.2, -1.6] # Custom reset pose for the left arm
    workspace_limits: {
            "low":[0.25469, -0.273459, -0.05, 3.03, -1.2, -1.60],
            "high":[0.4869, -0.18, 0.2, 3.03, -1.0, -1.6],
    }
    gripper_open_width: 0.04
    gripper_close_width: 0.00               # Custom gripper close width for the right arm
    cameras:                                # Custom camera configuration for the right arm
      wrist_cam:
        type: opencv
        index_or_path: 10
        width: 640
        height: 480
        fps: 30
      side_cam:
        type: opencv
        index_or_path: 16
        width: 640
        height: 480
        fps: 30

